### ISSUE TITLE
Run faster in Docker

### ISSUE THREAD

**Issue by earlbread** [planetarium/libplanet-explorer-frontend#20]
We can run this project as docker thanks to #18. However, it takes time to run because the image runs `npm run dev` every time. It would be better to build the static files when making the docker image and serve it when running the image.

**Comment by kmjayadeep** [comment]
Can I take this up?

**Comment by dahlia** [comment]
@kmjayadeep Of course, here you go! :+1:

**Comment by kmjayadeep** [comment]
Thanks! Expect a PR soon :)

**Comment by kmjayadeep** [comment]
I'm writing a docker-compose file too. What should I give as the name of the image? Are you planning to host the container in dockerhub?

**Comment by dahlia** [comment]
Oh, yes, it would be great if we can push images to Docker Hub!  The image name should be same to this GitHub repository name.

**Comment by kmjayadeep** [comment]
Okay, i will name it as planetarium/libplanet-explorer-frontend

**Comment by dahlia** [comment]
#33 fixed this.
