### ISSUE TITLE
Auto refresh when block mined

### ISSUE THREAD

**Issue by limebell** [planetarium/libplanet-explorer-frontend#37]
It will be great if the main block page is auto refreshed when new block is mined or the chain is swapped.

**Comment by MaxStalker** [comment]
@limebell I would like to help you with this one :)

**Comment by MaxStalker** [comment]
Stumbled into some road blocks here.
Apparently GraphQL API at http://52.231.65.77:5000/graphql/ is not responding.
Wanted to run my own locally, but that one requires **BLOCKCHAIN_STORE_PATH** - can you tell me what I shall put there?

**Comment by dahlia** [comment]
@MaxStalker Please try this dummy data: <https://send.firefox.com/download/2c48e7b706539261/#A3tl2924DprWW68LhDrtoA>. It's dumped from my local node.

**Comment by MaxStalker** [comment]
I would really appreciate if you can bring up public graphql endpoint 🙇‍♂️
I've encountered several issues with running local version of explorer, unfortunately 😟

**Comment by longfin** [comment]
> I would really appreciate if you can bring up public graphql endpoint 🙇‍♂️

@MaxStalker I'll launch public graphql endpoint. please wait for minutes.

**Comment by longfin** [comment]
> > I would really appreciate if you can bring up public graphql endpoint 🙇‍♂️
> 
> @MaxStalker I'll launch public graphql endpoint. please wait for minutes.

@MaxStalker Please try this endpoint.

http://52.231.74.24:31235/graphql

**Comment by MaxStalker** [comment]
Thank you @longfin!
This works perfectly ^__^

**Comment by MaxStalker** [comment]
After I've read through the code I have a feeling that issue is missing some critical points in description :)
- how one can check that new block was mined? Shall I setup polling and check if there are new blocks in response and then update the view? Or it's possible to setup subscriptions to specific event?
- "when the chain is swapped" - is this specific event or? How one can observe it?

**Comment by limebell** [comment]
> After I've read through the code I have a feeling that issue is missing some critical points in description :)
> 
> * how one can check that new block was mined? Shall I setup polling and check if there are new blocks in response and then update the view? Or it's possible to setup subscriptions to specific event?
> * "when the chain is swapped" - is this specific event or? How one can observe it?

@MaxStalker Sorry for late reply. Here's additional description for this issue.
* Currently, polling should be set because explorer does not have any event for it.
* If chain is swapped or new block is appened, blockchain's tip will be changed. So by observing blockchain's tip (tip is a blockchain's latest block), u can resolve this issue ;)

**Comment by dahlia** [comment]
At present, the easiest way to implement this would be setting up polling IMO?  Or we could declare a subscription at GraphQL level, but this needs to change code on libplanet-explorer (which is a .NET project).

**Comment by MaxStalker** [comment]
Roger.
Next one would be - is it possible to speed up block mining? Last one was mined 4 days ago, which a bit hard to track and check that UI updates correctly :)
Same for chain swap - any way to test it?

**Comment by limebell** [comment]
Sorry for inconvenience. Now block explorer is offline and using static blockchain file. We will gonna make it work online, server will be turned off for while 😥

**Comment by MaxStalker** [comment]
Got it.
I think I can mock the response to check that UI is updated properly and then will wait for news from your side ;)

**Comment by limebell** [comment]
Currently working on explorer, fixed some problems, still suffering on multiple issues :(

We will do our best and notify you as soon as explorer is online.

**Comment by limebell** [comment]
@MaxStalker Explorer is now online :)

**Comment by MaxStalker** [comment]
@longfin @limebell Can you bring that GraphQL api back online? :)
Can't reach it now :\

**Comment by longfin** [comment]
> @longfin @limebell Can you bring that GraphQL api back online? :)
> Can't reach it now :\

@MaxStalker I restarted API backend now. please check again.

**Comment by limebell** [comment]
Closed by #43.
