### ISSUE TITLE
Recent block interval, difficulty & hash rate

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet-explorer-frontend#4]
As like [Etherscan] shows the recent block interval, difficulty, and hash rate (see below), it would be useful if we have the similar thing.

![From Etherscan's home page](https://user-images.githubusercontent.com/12431/62996972-a9d79200-bea1-11e9-91d3-d3f9945ae780.png)

[Etherscan]: https://etherscan.io/

**Comment by aucch** [comment]
I worked on this.
