### ISSUE TITLE
Display count of transactions

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet-explorer-frontend#41]
In my thought, It will be better to display count of transactions if there are so many transactions or is nothing.

Let's see with screenshot. This is now.

![image](https://user-images.githubusercontent.com/26626194/67205135-0333e280-f44a-11e9-8761-0a7949ad77f0.png)

But isn't it better if it became like below or another?

![image](https://user-images.githubusercontent.com/26626194/67205447-be5c7b80-f44a-11e9-9081-66b7ba22073a.png)

**Comment by limebell** [comment]
Closed by #44.
