### ISSUE TITLE
Account page

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet-explorer-frontend#9]
A page that lists transactions related to an account.

**Comment by MaxStalker** [comment]
I can help you with this one If you have some outline how you want this to work :)
I guess, we can do something simillar to Etherscan, when you have a list of transactions in the block, then you click on a transaction, which will have details "from" or "to", which can be then used to display all related transactions on separate route.

Though it will require separate transaction route/view that is outside of the scope of this specific issue.

**Comment by MaxStalker** [comment]
Also, if possible, can you "create" several transactions, cause atm all blocks are empty :\

**Comment by limebell** [comment]
We are expecting to inspect these things in account page:
- Transactions that corresponding address created. (stored in `Transaction<T>.Signer`)
- Transactions that corresponding address related. (stored in `Transaction<T>.UpdatedAddress`)

It will be great if account page has table UI like main page, but if it is picky, just listing texts such as block page will do the work :)

**Comment by MaxStalker** [comment]
I'm using the following query to fetch transactions specific to certain account:
```
query TransactionsByAccount($involvedAddress: Address) {
  transactions(involvedAddress: $involvedAddress) {
    ...TransactionCommon
  }
}
```
When I try to fetch it with generated Apollo component it returns an error:
```
extensions: {code: "INVALID_CAST"}
code: "INVALID_CAST"
message: "Unable to cast object of type 'System.String' to type 'System.Nullable`1[Libplanet.Address]'."
```
Works in Insomnia without any problems:
![image](https://user-images.githubusercontent.com/3136647/67572662-54402100-f73f-11e9-8181-c2ca0343da86.png)

Any hints how to fix that?

**Comment by MaxStalker** [comment]
Can someone check and tell me if it's something wrong on front-end or API side? :)

**Comment by longfin** [comment]
> Can someone check and tell me if it's something wrong on front-end or API side? :)

@MaxStalker I've found related bug. I'll fix and update the backend API server in a minute.

**Comment by longfin** [comment]
@MaxStalker I updated the backend API as a fixed version. please check as below.

```
curl 'http://52.231.74.24:31235/graphql/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://52.231.74.24:31235' --data-binary '{"query":"query TransactionsByAccount($account: Address) {\n  transactions(involvedAddress: $account) {\n    id\n  }\n}","variables":{"account":"6510f821819937d70f6f8930BAC1BF7b39331aB1"}}' --compressed
```

**Comment by MaxStalker** [comment]
Thanks @longfin!
Works like a charm :)

**Comment by MaxStalker** [comment]
@longfin this one should be closed, right?

**Comment by longfin** [comment]
> @longfin this one should be closed, right?

Yes, thanks for reminding.
