### ISSUE TITLE
Can't set option dateStyle in TimeStamp Component for latest Firefox verision

### ISSUE THREAD

**Issue by x86chi** [planetarium/libplanet-explorer-frontend#92]
It seems that `9c-beta` endpoint has a below type error for latest Firefox version`79.x`. This error causes a blank screen.

> _TypeError: can't set option dateStyle in Date.toLocaleTimeString() in [TimeStamp.tsx:20](https://github.com/planetarium/libplanet-explorer-frontend/blob/b2186f4ff872ebdfb3f618feb7c0969aefe4e3f9/src/components/Timestamp.tsx#L20)_

## ScreenShot

<img width="1024" alt="Screen Shot 2020-07-29 at 2 13 59 PM" src="https://user-images.githubusercontent.com/5278201/88759449-c1d51e00-d1a5-11ea-8b5d-dd195d6c32f2.png">

**Comment by x86chi** [comment]
I found the resson why the error occurred. `dateStyle` and `timeStyle` in `Intl.DateTimeFormat` options is relatively recent specification. so some browsers [not yet implemented](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#Browser_compatibility).

I think it is difficult for all browsers to support timestamps in formats such as `7/29/20, 4:30 PM`, How about using a format 2-digit number? such as `4:31 PM`.

<img width="853" alt="Screen Shot 2020-07-29 at 4 40 00 PM" src="https://user-images.githubusercontent.com/5278201/88771402-28fccd80-d1ba-11ea-809b-ecfe761381dd.png">

**Comment by dahlia** [comment]
How about catching `TypeError` from `toLocaleString()` call, and falling back to the call to the same method without those recent options?
